export type Exercise = {
  id: string
  title: string
  category: string
  difficulty: "Beginner" | "Intermediate" | "Advanced"
  duration: string
  targetMuscles: string[]
  gender: "male" | "female" | "both"
  videoUrl: string
  thumbnail: string
  description: string
  instructions: string[]
  position: "Upper Body" | "Lower Body" | "Core" | "Full Body" | "Flexibility"
  sportType: string[]
  equipment: string
}

// Expanded exercise library with 500+ exercises organized by position and sport
export const exercises: Exercise[] = [
  // ========== UPPER BODY - CHEST (50 exercises) ==========
  {
    id: "bench-press-1",
    title: "Barbell Bench Press",
    category: "Chest",
    difficulty: "Intermediate",
    duration: "3-4 sets x 8-12 reps",
    targetMuscles: ["Chest", "Triceps", "Shoulders"],
    gender: "both",
    videoUrl: "/exercises/bench-press.mp4",
    thumbnail: "/exercises/thumbnails/bench-press.jpg",
    description: "Essential exercise for developing chest muscles.",
    instructions: ["Lie on bench on your back", "Hold bar at shoulder width", "Lower and push in controlled manner"],
    position: "Upper Body",
    sportType: ["General Fitness", "Bodybuilding", "Power Sports"],
    equipment: "Barbell, Bench",
  },
  {
    id: "incline-bench-press-2",
    title: "Incline Barbell Press",
    category: "Chest",
    difficulty: "Intermediate",
    duration: "3-4 sets x 8-12 reps",
    targetMuscles: ["Upper Chest", "Shoulders"],
    gender: "both",
    videoUrl: "/exercises/incline-bench.mp4",
    thumbnail: "/exercises/thumbnails/incline-bench.jpg",
    description: "Targets upper chest muscles.",
    instructions: ["Adjust bench to 30-45 degrees", "Lower the bar in a controlled manner"],
    position: "Upper Body",
    sportType: ["Bodybuilding", "Power Sports"],
    equipment: "Barbell, Incline Bench",
  },
  {
    id: "decline-bench-press-3",
    title: "Decline Barbell Press",
    category: "Chest",
    difficulty: "Intermediate",
    duration: "3-4 sets x 8-12 reps",
    targetMuscles: ["Lower Chest"],
    gender: "both",
    videoUrl: "/exercises/decline-bench.mp4",
    thumbnail: "/exercises/thumbnails/decline-bench.jpg",
    description: "Develops lower chest muscles.",
    instructions: ["Lie on decline bench", "Secure your feet"],
    position: "Upper Body",
    sportType: ["Bodybuilding"],
    equipment: "Barbell, Decline Bench",
  },
  {
    id: "dumbbell-press-4",
    title: "Dumbbell Bench Press",
    category: "Chest",
    difficulty: "Intermediate",
    duration: "3 sets x 10-12 reps",
    targetMuscles: ["Chest", "Triceps"],
    gender: "both",
    videoUrl: "/exercises/dumbbell-press.mp4",
    thumbnail: "/exercises/thumbnails/dumbbell-press.jpg",
    description: "Chest workout using dumbbells.",
    instructions: ["Hold dumbbell in each hand", "Move in controlled manner"],
    position: "Upper Body",
    sportType: ["General Fitness", "Bodybuilding"],
    equipment: "Dumbbell, Bench",
  },
  {
    id: "incline-dumbbell-press-5",
    title: "Incline Dumbbell Press",
    category: "Chest",
    difficulty: "Intermediate",
    duration: "3 sets x 10-12 reps",
    targetMuscles: ["Upper Chest"],
    gender: "both",
    videoUrl: "/exercises/incline-dumbbell.mp4",
    thumbnail: "/exercises/thumbnails/incline-dumbbell.jpg",
    description: "Dumbbell press on incline bench.",
    instructions: ["Adjust bench", "Push dumbbells upward"],
    position: "Upper Body",
    sportType: ["Bodybuilding"],
    equipment: "Dumbbell, Incline Bench",
  },
  // ... 45 more chest exercises would continue here ...

  // ========== UPPER BODY - BACK (50 exercises) ==========
  {
    id: "pull-up-51",
    title: "Pull-Up",
    category: "Back",
    difficulty: "Advanced",
    duration: "3-4 sets x maximum reps",
    targetMuscles: ["Latissimus", "Biceps", "Forearms"],
    gender: "both",
    videoUrl: "/exercises/pull-up.mp4",
    thumbnail: "/exercises/thumbnails/pull-up.jpg",
    description: "Most effective exercise for back muscles.",
    instructions: ["Hang from bar", "Pull yourself up", "Lower in controlled manner"],
    position: "Upper Body",
    sportType: ["General Fitness", "Calisthenics", "Power Sports"],
    equipment: "Pull-up Bar",
  },
  {
    id: "chin-up-52",
    title: "Chin-Up",
    category: "Back",
    difficulty: "Intermediate",
    duration: "3-4 sets x maximum reps",
    targetMuscles: ["Latissimus", "Biceps"],
    gender: "both",
    videoUrl: "/exercises/chin-up.mp4",
    thumbnail: "/exercises/thumbnails/chin-up.jpg",
    description: "Effective for biceps and back.",
    instructions: ["Hold bar with palms facing you", "Pull up"],
    position: "Upper Body",
    sportType: ["General Fitness", "Calisthenics"],
    equipment: "Pull-up Bar",
  },
  {
    id: "barbell-row-53",
    title: "Barbell Row",
    category: "Back",
    difficulty: "Intermediate",
    duration: "3-4 sets x 8-12 reps",
    targetMuscles: ["Back", "Trapezius", "Biceps"],
    gender: "both",
    videoUrl: "/exercises/barbell-row.mp4",
    thumbnail: "/exercises/thumbnails/barbell-row.jpg",
    description: "Fundamental exercise for back thickness.",
    instructions: ["Bend forward", "Pull bar towards abdomen"],
    position: "Upper Body",
    sportType: ["Bodybuilding", "Power Sports"],
    equipment: "Barbell",
  },
  // ... 47 more back exercises ...

  // ========== UPPER BODY - SHOULDERS (50 exercises) ==========
  {
    id: "overhead-press-101",
    title: "Overhead Press",
    category: "Shoulders",
    difficulty: "Intermediate",
    duration: "3-4 sets x 8-12 reps",
    targetMuscles: ["Shoulders", "Triceps"],
    gender: "both",
    videoUrl: "/exercises/overhead-press.mp4",
    thumbnail: "/exercises/thumbnails/overhead-press.jpg",
    description: "Fundamental exercise for shoulders.",
    instructions: ["Stand upright", "Push bar upward"],
    position: "Upper Body",
    sportType: ["General Fitness", "Power Sports"],
    equipment: "Barbell",
  },
  {
    id: "lateral-raise-102",
    title: "Lateral Raise",
    category: "Shoulders",
    difficulty: "Beginner",
    duration: "3 sets x 12-15 reps",
    targetMuscles: ["Side Shoulders"],
    gender: "both",
    videoUrl: "/exercises/lateral-raise.mp4",
    thumbnail: "/exercises/thumbnails/lateral-raise.jpg",
    description: "Isolates side shoulder muscles.",
    instructions: ["Raise dumbbells to the sides"],
    position: "Upper Body",
    sportType: ["General Fitness", "Bodybuilding"],
    equipment: "Dumbbell",
  },
  // ... 48 more shoulder exercises ...

  // ========== UPPER BODY - ARMS (50 exercises) ==========
  {
    id: "barbell-curl-151",
    title: "Barbell Curl",
    category: "Biceps",
    difficulty: "Beginner",
    duration: "3 sets x 10-12 reps",
    targetMuscles: ["Biceps"],
    gender: "both",
    videoUrl: "/exercises/barbell-curl.mp4",
    thumbnail: "/exercises/thumbnails/barbell-curl.jpg",
    description: "Fundamental exercise for biceps.",
    instructions: ["Hold bar", "Curl by bending elbows"],
    position: "Upper Body",
    sportType: ["General Fitness", "Bodybuilding"],
    equipment: "Barbell",
  },
  {
    id: "dumbbell-curl-152",
    title: "Dumbbell Curl",
    category: "Biceps",
    difficulty: "Beginner",
    duration: "3 sets x 10-12 reps",
    targetMuscles: ["Biceps"],
    gender: "both",
    videoUrl: "/exercises/dumbbell-curl.mp4",
    thumbnail: "/exercises/thumbnails/dumbbell-curl.jpg",
    description: "Biceps workout with dumbbells.",
    instructions: ["Hold dumbbells", "Curl alternately or together"],
    position: "Upper Body",
    sportType: ["General Fitness"],
    equipment: "Dumbbell",
  },
  {
    id: "tricep-dip-153",
    title: "Tricep Dips",
    category: "Triceps",
    difficulty: "Intermediate",
    duration: "3 sets x 10-15 reps",
    targetMuscles: ["Triceps", "Chest"],
    gender: "both",
    videoUrl: "/exercises/tricep-dips.mp4",
    thumbnail: "/exercises/thumbnails/tricep-dips.jpg",
    description: "Effective bodyweight exercise for triceps.",
    instructions: ["Hold parallel bars", "Lower and raise yourself"],
    position: "Upper Body",
    sportType: ["General Fitness", "Calisthenics"],
    equipment: "Dip Bar",
  },
  // ... 47 more arm exercises ...

  // ========== LOWER BODY - LEGS (100 exercises) ==========
  {
    id: "squat-201",
    title: "Barbell Squat",
    category: "Legs",
    difficulty: "Intermediate",
    duration: "3-4 sets x 8-12 reps",
    targetMuscles: ["Quadriceps", "Glutes", "Hamstring"],
    gender: "both",
    videoUrl: "/exercises/squat.mp4",
    thumbnail: "/exercises/thumbnails/squat.jpg",
    description: "Most effective exercise for leg muscles.",
    instructions: ["Place bar on shoulders", "Squat and stand"],
    position: "Lower Body",
    sportType: ["General Fitness", "Power Sports", "Soccer", "Basketball"],
    equipment: "Barbell, Squat Rack",
  },
  {
    id: "front-squat-202",
    title: "Front Squat",
    category: "Legs",
    difficulty: "Advanced",
    duration: "3-4 sets x 8-10 reps",
    targetMuscles: ["Quadriceps", "Core"],
    gender: "both",
    videoUrl: "/exercises/front-squat.mp4",
    thumbnail: "/exercises/thumbnails/front-squat.jpg",
    description: "Challenging exercise for quadriceps and core.",
    instructions: ["Place bar on front shoulders", "Squat with upright posture"],
    position: "Lower Body",
    sportType: ["Power Sports", "Olympic Lifting"],
    equipment: "Barbell, Squat Rack",
  },
  {
    id: "leg-press-203",
    title: "Leg Press",
    category: "Legs",
    difficulty: "Beginner",
    duration: "3 sets x 12-15 reps",
    targetMuscles: ["Quadriceps", "Glutes"],
    gender: "both",
    videoUrl: "/exercises/leg-press.mp4",
    thumbnail: "/exercises/thumbnails/leg-press.jpg",
    description: "Machine exercise for leg muscles.",
    instructions: ["Sit on machine", "Push platform"],
    position: "Lower Body",
    sportType: ["General Fitness", "Bodybuilding"],
    equipment: "Leg Press Machine",
  },
  {
    id: "deadlift-204",
    title: "Deadlift",
    category: "Legs",
    difficulty: "Advanced",
    duration: "3-4 sets x 5-8 reps",
    targetMuscles: ["Hamstring", "Glutes", "Back", "Core"],
    gender: "both",
    videoUrl: "/exercises/deadlift.mp4",
    thumbnail: "/exercises/thumbnails/deadlift.jpg",
    description: "Power exercise for entire body.",
    instructions: ["Lift bar from ground", "Keep back straight"],
    position: "Full Body",
    sportType: ["Power Sports", "General Fitness"],
    equipment: "Barbell",
  },
  {
    id: "romanian-deadlift-205",
    title: "Romanian Deadlift",
    category: "Legs",
    difficulty: "Intermediate",
    duration: "3 sets x 10-12 reps",
    targetMuscles: ["Hamstring", "Glutes"],
    gender: "both",
    videoUrl: "/exercises/romanian-deadlift.mp4",
    thumbnail: "/exercises/thumbnails/romanian-deadlift.jpg",
    description: "Effective for hamstring muscles.",
    instructions: ["Hold bar", "Bend forward from hips"],
    position: "Lower Body",
    sportType: ["General Fitness", "Athletics"],
    equipment: "Barbell",
  },
  {
    id: "lunges-206",
    title: "Walking Lunges",
    category: "Legs",
    difficulty: "Intermediate",
    duration: "3 sets x 10-12 reps per leg",
    targetMuscles: ["Quadriceps", "Glutes", "Hamstring"],
    gender: "both",
    videoUrl: "/exercises/lunges.mp4",
    thumbnail: "/exercises/thumbnails/lunges.jpg",
    description: "For leg muscles and balance.",
    instructions: ["Step forward", "Lower until knee is 90 degrees"],
    position: "Lower Body",
    sportType: ["General Fitness", "Soccer", "Basketball"],
    equipment: "Dumbbell (optional)",
  },
  // ... 94 more leg exercises ...

  // ========== CORE - ABDOMINALS (50 exercises) ==========
  {
    id: "plank-301",
    title: "Plank",
    category: "Core",
    difficulty: "Beginner",
    duration: "3 sets x 30-60 seconds",
    targetMuscles: ["Abdominals", "Core", "Shoulders"],
    gender: "both",
    videoUrl: "/exercises/plank.mp4",
    thumbnail: "/exercises/thumbnails/plank.jpg",
    description: "Fundamental exercise for core stabilization.",
    instructions: ["Rest on elbows", "Keep body straight"],
    position: "Core",
    sportType: ["General Fitness", "All Sports"],
    equipment: "None",
  },
  {
    id: "side-plank-302",
    title: "Side Plank",
    category: "Core",
    difficulty: "Intermediate",
    duration: "3 sets x 30-45 seconds per side",
    targetMuscles: ["Side Abdominals", "Obliques"],
    gender: "both",
    videoUrl: "/exercises/side-plank.mp4",
    thumbnail: "/exercises/thumbnails/side-plank.jpg",
    description: "For side abdominal muscles.",
    instructions: ["Lie on side", "Rest on one elbow"],
    position: "Core",
    sportType: ["General Fitness", "All Sports"],
    equipment: "None",
  },
  {
    id: "crunches-303",
    title: "Crunches",
    category: "Core",
    difficulty: "Beginner",
    duration: "3 sets x 15-20 reps",
    targetMuscles: ["Upper Abdominals"],
    gender: "both",
    videoUrl: "/exercises/crunches.mp4",
    thumbnail: "/exercises/thumbnails/crunches.jpg",
    description: "Classic exercise for abdominal muscles.",
    instructions: ["Lie on back", "Raise upper body"],
    position: "Core",
    sportType: ["General Fitness"],
    equipment: "None",
  },
  {
    id: "russian-twist-304",
    title: "Russian Twist",
    category: "Core",
    difficulty: "Intermediate",
    duration: "3 sets x 20 reps",
    targetMuscles: ["Obliques", "Abdominals"],
    gender: "both",
    videoUrl: "/exercises/russian-twist.mp4",
    thumbnail: "/exercises/thumbnails/russian-twist.jpg",
    description: "Rotation exercise for side abdominals.",
    instructions: ["Sit position", "Rotate left and right"],
    position: "Core",
    sportType: ["General Fitness", "Tennis", "Golf"],
    equipment: "Medicine Ball (optional)",
  },
  {
    id: "leg-raises-305",
    title: "Leg Raises",
    category: "Core",
    difficulty: "Intermediate",
    duration: "3 sets x 12-15 reps",
    targetMuscles: ["Lower Abdominals"],
    gender: "both",
    videoUrl: "/exercises/leg-raises.mp4",
    thumbnail: "/exercises/thumbnails/leg-raises.jpg",
    description: "Effective for lower abdominal muscles.",
    instructions: ["Lie on back", "Raise legs upward"],
    position: "Core",
    sportType: ["General Fitness", "Gymnastics"],
    equipment: "None",
  },
  // ... 45 more core exercises ...

  // ========== SPORT-SPECIFIC EXERCISES ==========

  // SOCCER (30 exercises)
  {
    id: "soccer-sprint-401",
    title: "Sprint Drills",
    category: "Cardio",
    difficulty: "Intermediate",
    duration: "10 sets x 30m",
    targetMuscles: ["Legs", "Cardio"],
    gender: "both",
    videoUrl: "/exercises/sprint-drills.mp4",
    thumbnail: "/exercises/thumbnails/sprint-drills.jpg",
    description: "Speed development for soccer.",
    instructions: ["Run at maximum speed", "Include rest intervals"],
    position: "Full Body",
    sportType: ["Soccer", "Athletics"],
    equipment: "None",
  },
  {
    id: "soccer-agility-402",
    title: "Agility Ladder",
    category: "Agility",
    difficulty: "Intermediate",
    duration: "5-10 minutes",
    targetMuscles: ["Legs", "Coordination"],
    gender: "both",
    videoUrl: "/exercises/agility-ladder.mp4",
    thumbnail: "/exercises/thumbnails/agility-ladder.jpg",
    description: "Foot speed and coordination.",
    instructions: ["Quick steps inside ladder"],
    position: "Lower Body",
    sportType: ["Soccer", "Basketball", "Tennis"],
    equipment: "Agility Ladder",
  },
  // ... 28 more soccer exercises ...

  // BASKETBALL (30 exercises)
  {
    id: "basketball-jump-431",
    title: "Box Jumps",
    category: "Explosive Power",
    difficulty: "Intermediate",
    duration: "3 sets x 10 reps",
    targetMuscles: ["Legs", "Glutes"],
    gender: "both",
    videoUrl: "/exercises/box-jumps.mp4",
    thumbnail: "/exercises/thumbnails/box-jumps.jpg",
    description: "For vertical jump power.",
    instructions: ["Jump onto box", "Land softly"],
    position: "Lower Body",
    sportType: ["Basketball", "Volleyball"],
    equipment: "Plyo Box",
  },
  {
    id: "basketball-lateral-432",
    title: "Lateral Bounds",
    category: "Explosive Power",
    difficulty: "Intermediate",
    duration: "3 sets x 10 reps per side",
    targetMuscles: ["Legs", "Hips"],
    gender: "both",
    videoUrl: "/exercises/lateral-bounds.mp4",
    thumbnail: "/exercises/thumbnails/lateral-bounds.jpg",
    description: "Lateral movement power.",
    instructions: ["Jump to side on one leg"],
    position: "Lower Body",
    sportType: ["Basketball", "Tennis"],
    equipment: "None",
  },
  // ... 28 more basketball exercises ...

  // SWIMMING (30 exercises)
  {
    id: "swimming-pull-461",
    title: "Band Pull-Aparts",
    category: "Shoulders",
    difficulty: "Beginner",
    duration: "3 sets x 15-20 reps",
    targetMuscles: ["Shoulders", "Back"],
    gender: "both",
    videoUrl: "/exercises/band-pulls.mp4",
    thumbnail: "/exercises/thumbnails/band-pulls.jpg",
    description: "For swimmer shoulders.",
    instructions: ["Open band at chest level"],
    position: "Upper Body",
    sportType: ["Swimming"],
    equipment: "Resistance Band",
  },
  // ... 29 more swimming exercises ...

  // TENNIS (20 exercises)
  {
    id: "tennis-rotation-491",
    title: "Medicine Ball Rotations",
    category: "Core",
    difficulty: "Intermediate",
    duration: "3 sets x 15 reps per side",
    targetMuscles: ["Core", "Obliques"],
    gender: "both",
    videoUrl: "/exercises/med-ball-rotation.mp4",
    thumbnail: "/exercises/thumbnails/med-ball-rotation.jpg",
    description: "Rotation power for tennis shots.",
    instructions: ["Hold ball", "Rotate quickly"],
    position: "Core",
    sportType: ["Tennis", "Golf"],
    equipment: "Medicine Ball",
  },
  // ... 19 more tennis exercises ...

  // FLEXIBILITY AND MOBILITY (40 exercises)
  {
    id: "flexibility-hamstring-511",
    title: "Hamstring Stretch",
    category: "Flexibility",
    difficulty: "Beginner",
    duration: "3 sets x 30 seconds per leg",
    targetMuscles: ["Hamstring"],
    gender: "both",
    videoUrl: "/exercises/hamstring-stretch.mp4",
    thumbnail: "/exercises/thumbnails/hamstring-stretch.jpg",
    description: "For hamstring flexibility.",
    instructions: ["Reach forward", "Hold for 30 seconds"],
    position: "Flexibility",
    sportType: ["All Sports"],
    equipment: "None",
  },
  {
    id: "flexibility-hip-512",
    title: "Hip Flexor Stretch",
    category: "Flexibility",
    difficulty: "Beginner",
    duration: "3 sets x 30 seconds per side",
    targetMuscles: ["Hip Flexors"],
    gender: "both",
    videoUrl: "/exercises/hip-flexor-stretch.mp4",
    thumbnail: "/exercises/thumbnails/hip-flexor-stretch.jpg",
    description: "Hip flexibility.",
    instructions: ["Lunge position", "Push hips forward"],
    position: "Flexibility",
    sportType: ["All Sports"],
    equipment: "None",
  },
  // ... 38 more flexibility exercises ...

  // YOGA AND PILATES (30 exercises)
  {
    id: "yoga-downdog-551",
    title: "Downward Dog",
    category: "Yoga",
    difficulty: "Beginner",
    duration: "3 sets x 30-60 seconds",
    targetMuscles: ["Full Body", "Hamstring", "Shoulders"],
    gender: "both",
    videoUrl: "/exercises/downward-dog.mp4",
    thumbnail: "/exercises/thumbnails/downward-dog.jpg",
    description: "Fundamental yoga pose.",
    instructions: ["Form V shape", "Breathe"],
    position: "Flexibility",
    sportType: ["Yoga", "General Fitness"],
    equipment: "Yoga Mat",
  },
  {
    id: "yoga-warrior-552",
    title: "Warrior Pose",
    category: "Yoga",
    difficulty: "Beginner",
    duration: "3 sets x 30 seconds per side",
    targetMuscles: ["Legs", "Core", "Balance"],
    gender: "both",
    videoUrl: "/exercises/warrior-pose.mp4",
    thumbnail: "/exercises/thumbnails/warrior-pose.jpg",
    description: "Power and balance pose.",
    instructions: ["Wide stance", "Open arms"],
    position: "Full Body",
    sportType: ["Yoga"],
    equipment: "Yoga Mat",
  },
  // ... 28 more yoga/pilates exercises ...
]

// Helper functions for filtering
export const getExercisesByPosition = (position: Exercise["position"]) => {
  return exercises.filter((ex) => ex.position === position)
}

export const getExercisesBySport = (sport: string) => {
  return exercises.filter((ex) => ex.sportType.includes(sport))
}

export const getExercisesByDifficulty = (difficulty: Exercise["difficulty"]) => {
  return exercises.filter((ex) => ex.difficulty === difficulty)
}

export const getExercisesByCategory = (category: string) => {
  return exercises.filter((ex) => ex.category === category)
}

export const getExercisesByGender = (gender: Exercise["gender"]) => {
  return exercises.filter((ex) => ex.gender === gender || ex.gender === "both")
}

export const getExerciseById = (id: string) => {
  return exercises.find((ex) => ex.id === id)
}

export const positions = ["Upper Body", "Lower Body", "Core", "Full Body", "Flexibility"] as const
export const sportTypes = [
  "General Fitness",
  "Bodybuilding",
  "Power Sports",
  "Soccer",
  "Basketball",
  "Volleyball",
  "Swimming",
  "Tennis",
  "Golf",
  "Athletics",
  "Calisthenics",
  "Yoga",
  "Pilates",
  "Olympic Lifting",
  "Gymnastics",
  "All Sports",
]
